name: Publish

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn
      
      - name: Publish package
        run: yarn publish --new-version $(git describe --abbrev=0)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
